### PR TITLE
workaround for mississippi.finished (end-of-stream) intermitent failures

### LINKED ISSUE #143: spurious ENOVERSIONS on git dependencies
we've been seeing random failures both on our CI and our dev machines that didn't make sense. npm was failing to see any valid versions for a random git dependency in the tree

I spent some hours investigating the issue, and within the scope of pacote, it boils down to an issue with when `finished` ends up resolving the promise, and that is "too soon", as in I observe stdout and stderr being empty strings when execution reaches `REVS.set(repo, revs)` on https://github.com/zkat/pacote/blob/latest/lib/util/git.js#L178

The way that I isolated the issue was by replacing `finished` with a naïve `onclose` which does not end up with empty `stdout` or if it does, then it has a lower chance for some reason. I have not experienced any issues in a 100-times trial. I didn't move into debugging the `end-of-stream` package (=`finished`).

Naïve `onclose` replacement (I say naïve because I guess there are reasons why pacote uses `end-of-stream`, which I do not know of):

```js
    /*return finished(child).catch(err => {
        err.message = `Error while executing:\n${GITPATH} ls-remote -h -t ${repo}\n\n${stderr}\n${err.message}`
        throw err
      }).then(() => {*/
      return (new Promise(function(resolve, reject) {
        child.on('error', reject).on('close', function(code) {
          if (code === 0) {
            resolve();
          } else {
            let err = new Error(`Error while executing:\n${GITPATH} ls-remote -h -t ${repo}\n\n${stderr}\n${err.message}`);
            reject(err);
          }
        })
      })).then(() => {

```

The 100-times trial was run with this `package.json`, executing in a git repo that has only this file checked in - `git clean -xdf; npm i` (npm@5.7.1)

```json
{
  "private": true,
  "name": "lodash-firecloud",
  "version": "0.1.2",
  "dependencies": {
    "babel-preset-firecloud": "git://github.com/tobiipro/babel-preset-firecloud.git#semver:~0.1.2",
    "eslint-config-firecloud": "git://github.com/tobiipro/eslint-config-firecloud.git#semver:~0.1.2",
    "eslint-plugin-firecloud": "git://github.com/tobiipro/eslint-plugin-firecloud.git#semver:~0.1.0",
    "npm-publish-git": "git://github.com/andreineculau/npm-publish-git.git#semver:~0.0.7"
  }
}
```

The same `package.json` would fail with ENOVERSIONS on any of the -firecloud deps, maybe even npm-publish-git though I did not experience that in my trials.

Ref: internal reported issue with links to Travis CI runs https://github.com/tobiipro/support-firecloud/issues/17

### PR DESCRIPTION
**Pull request by andreineculau**
should fix https://github.com/zkat/pacote/issues/143

### CODE REVIEW

**Comment by zkat** [comment]
https://travis-ci.org/zkat/pacote/jobs/360064813 This seems to still be having intermittent failures on CI :(

**Review by zkat — CHANGES_REQUESTED** [review]
I'm not sure this is actually fixing what it's meaning to fix, though the fix looks nominally right.

**Comment by andreineculau** [comment]
hmm ENOPACKAGEJSON this time.
Am I right to assume that this can be triggered via the `finalize-manifest.js` code?

I have initially replaced `finished` in there as well, but got some errors that I didn't have the time to look into, and I also thought that the fix is over-reaching since my goal was fixing `git clone`

Commit https://github.com/zkat/pacote/commit/15e4ddf715e87e7746067a22e7a9d4c3c7e0e5b1
Travi CI run https://travis-ci.org/zkat/pacote/jobs/360057598

**Comment by andreineculau** [comment]
all green now

**Review by zkat — APPROVED** [review]

**Comment by zkat** [comment]
I hate heisenbugs, but we may as well try this out and see what happens :\

**Comment by andreineculau** [comment]
Any chance of having a pacote release? This way all my team mates can get to confirm or not that the fix is working

**Pull request merged**
