### PR TITLE
fix(license): relicense to MIT for OSI-compat

### PR DESCRIPTION
**Pull request by zkat**
BREAKING CHANGE: The license has changed from CC0-1.0 to MIT, which is less permissive and also OSI-approved.

This goes along with some other relicensing going on in npm-related libraries, due to compatibility issues. This relicensing requires word from all prior contributors, so here we go! Please respond to this issue if your name is below to confirm you're ok with this, or ask any questions:

* [x] @iarna
* [x] @varjmes
* [x] @zarenner
* [x] @jozemlakar
* [x] @colinrotherham
* [ ] @mcibique
* [x] @keithamus
* [x] @strugee
* [x] @BridgeAR
* [x] @mistydemeo
* [x] @nlkluth
* [x] @tgandrews

### CODE REVIEW

**Comment by strugee** [comment]
LGTM :thumbsup:

But shouldn't this be a non-issue since CC0 lets you do _anything_, including relicensing?

**Comment by strugee** [comment]
Also FWIW I changed two characters (see #103) so tbh I wouldn't have copyright by any stretch of the imagination

**Comment by mistydemeo** [comment]
I'm 👍 on the change!

**Comment by BridgeAR** [comment]
:+1:

**Comment by keithamus** [comment]
👍 absolutely cool by me 😄

**Comment by nlkluth** [comment]
:+1:

**Comment by colinrotherham** [comment]
Yeah no problem at all, I'm happy with that. Thanks

**Comment by tgandrews** [comment]
No problem with me. Go ahead and change the license 👍

**Comment by varjmes** [comment]
Ya

**Comment by zarenner** [comment]
👍

**Comment by zkat** [comment]
@jozemlakar @mcibique hopeful ping

**Comment by jozemlakar** [comment]
Sry, thought absence of comment is equal to consent. I’m cool with the change!

**Comment by zkat** [comment]
@mcibique unfortunately, since I couldn't get a response from you, I decided to revert your commit to pacote. If you'd like to have it go back in (that test was really nice!) please email me with whether you're ok with the license change, and I'll make sure your code's added back in, under MIT.

**Comment by zkat** [comment]
I've merged this into `latest`. Thanks, everyone!

**Pull request closed without merging**
