### PR TITLE
debug: using tap's stdout-dejank branch

### PR DESCRIPTION
**Pull request by isaacs**
A pr against https://github.com/zkat/pacote/pull/13

### CODE REVIEW

**Comment by isaacs** [comment]
ok, well, that didn't work.

I have no idea how it's managing to exit without that output happening.  It's really strange.

But now I have a stable appveyor job I can re-try by pushing to that tap branch, so there's at least some kind of repro/debug cycle, albeit painfully slow.

**Comment by zkat** [comment]
Thanks for this, and lmk if there's anything I can do to help. (and of course, feel free to headdesk on this PR all you want)

**Comment by isaacs** [comment]
Fascinating trail of bugs here!

It turned out to have nothing to do with stdout flushing or any of that, as far as I can tell.

A bug in node-tap caused it to obscure errors where the final test in a set was not finished, and did not ever push any output.  But that wasn't the root cause.  But that's why `exit` seems to be firing sooner than it should, because it's legitimately hitting the process exit before it ends the tests.

That last test in the set is not ever getting fired, because the `fetcher` function never executes its callback.  Fixing the error-obscuring bug in node-tap makes it fail [like this](https://ci.appveyor.com/project/zkat/pacote/build/1.0.164/job/03gvlp0g49yk2en6), but I have no idea why the fetcher callback isn't being fired for that test sometimes.

**Comment by zkat** [comment]
@isaacs thanks a lot for the help! I converted `test-dir` to be async, and everything is nice and green now. See #13. So, I'm gonna close this one!

**Pull request closed without merging**
